### ISSUE TITLE
Difference to styled-breakpoints?

### ISSUE THREAD

**Issue by polarathene** [dvpnt/styled-media-helper#12]
Is this package different from [`styled-breakpoints`](https://github.com/mg901/styled-breakpoints)? Or offering the same functionality?

**Comment by Kuboczoch** [comment]
@polarathene I'm not a contributor to this project but I think it has a better spell checking by default, because of the code structure. Example of `styled-breakpoints` in Webstorm: 
![image](https://user-images.githubusercontent.com/20823919/85535809-d0fb0600-b612-11ea-9064-b8a69e471874.png)
Even with a plugin for styled-components content is always shown as a string instead of a CSS fragment.

**Comment by polarathene** [comment]
@Kuboczoch `styled-breakpoints` README shows syntax like you used in `styled-media-helper` example, expression only used for the query, then back to CSS, not all in single expression using template tag like 1st example.

**Comment by Kuboczoch** [comment]
@polarathene Oh my bad, I was talking about `styled-components-breakpoint`. Then my first argument is invalid sorry.

**Comment by shtyr-maxim** [comment]
@polarathene they both have an approximately similar syntax. What is the main things of this issue?

**Comment by polarathene** [comment]
@shtyr-maxim no issue, just asking if there was anything that might differentiate between the two offerings.  

`styled-breakpoints` presently has more stars and clearer documentation, but both are actively developed. Nothing wrong with that though :)

I will close the issue, if later someone notices a difference to set the two apart, please let me know!

**Comment by shtyr-maxim** [comment]
there was no `styled-breakpoints` package in [awesome-styled-components](https://github.com/styled-components/awesome-styled-components) at the time of creation this package. And now we have a two package with similar syntax 🙂

**Comment by polarathene** [comment]
Differences have been noticed:

1) `styled-media-helper` exports a class with query methods attached(can't destructure), while `styled-breakpoints` exports individual methods(should be able to group them under a common name with import syntax though)

2) `styled-media-helper` being a class can take a new instance, supporting multiple sets of breakpoints for responsive needs beyond standard device breakpoints, while `styled-breakpoints` can only use it's defaults or an override via a ThemeProvider.
